name = "ghtnhcm"
main = "worker.js"
compatibility_date = "2026-08-16"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ghtnhcm"
database_id = "56654304-9c6b-4e00-aaee-0d777526e762"
